aronfraga/gym-frontend-app

- src/components/Footer/Footer.jsx
- src/components/Footer/Footer.module.css
- src/components/Home/Home.jsx
> avance footer component

- src/components/Home/Home.jsx
agregue la navbar y footer de manu y ale
> footer and navbar added to home

- .gitignore
- src/components/Carousel/Carrusel.jsx
Solamente toque el carrusel...
> Arregle el tiempo del carrusel

- src/components/Footer/Footer.jsx
- src/components/Footer/Footer.module.css
- src/components/Footer/Helpers.js
> responsive design Footer

- src/App.jsx
- src/components/Home/Home.jsx
- src/components/NoMatch/NoMatch.jsx
- src/components/Routines/Routines.jsx
- src/main.jsx
Agregue el ruteo correctamente con las rutas que vamos a utilizar
> route fixed

- src/App.jsx
- src/components/Home/Home.jsx
- src/components/Login/Login.jsx
- src/components/NavBar/NavBar.jsx
> Updates in routes

- src/components/Filters/Filters.jsx
- src/components/Filters/Filters.module.css
> Component filters

- src/components/AllRoutines/AllRoutines.jsx
- src/components/Home/Home.jsx
- src/components/Routine/Routine.jsx
- src/components/Routines/Routines.jsx
Se crearon las card para renderizar las rutinas, y se modularizo sos contenedores. 
Se borro el componente Landing que no se estaba utilizando
se borro boton home
> routines card and external components

- src/components/NavBar/NavBar.jsx
> NavBar actualizada

- .gitignore
- package-lock.json
- src/components/Carousel/Banner.jsx
- src/components/Carousel/Carrusel.jsx
Arregle lel higth de las imagenes asi se le ce el pelo a la mujer... Lo de las animaciones no se como arreglarlos sin sacarlas
> Carrusel fixeado

- src/components/AllRoutines/AllRoutines.jsx
- src/components/AllRoutines/AllRoutines.module.css
- src/components/ContainerFilters/ContainerFilters.jsx
- src/components/ContainerFilters/ContainerFilters.module.css
- src/components/Filters/Filters.jsx
- src/components/Filters/Filters.module.css
- src/components/Routine/Routine.jsx
- src/components/Routine/Routine.module.css
- src/components/Routines/Routines.jsx
- src/components/Routines/Routines.module.css
Creé module css para algunos componentes, hardcodeado las rutinas en AllRoutines porque estaba caído el server, también hardcodeado la info de los filters en containerFilters.
> Routines commit 1

- src/App.jsx
- src/components/FormRoutines/FormRoutines.jsx
- src/redux/query/api.js
Bueno... Hice la querys.. Hay que fijarse que las hice pegandole a la ruta localhost:3001 (se cayo el deploy)... Ademas hice el formulario, no esta completo porque hay que arreglar 1 cosita desde el back.. Ademas que esta sin 1 solo estilo... Revisen un toque si quieren pero deje todo funcionando, pero son las 6:20 asi que pueden haber fallos...
> querys y form

- src/App.jsx
- src/components/FeedBack/FeedBack.jsx
- src/components/FeedBack/FeedBack.module.css
> Add component FeedBack

- src/components/BtnFilter/BtnFilter.jsx
- src/components/BtnFilter/BtnFilter.module.css
- src/components/BtnRoutines/BtnRoutines.jsx
- src/components/BtnRoutines/BtnRoutines.module.css
- src/components/Routines/Routines.jsx
agregue la botonera para los filtros
> btn for filter created

- src/components/FeedBack/FeedBack.jsx
- src/components/FeedBack/FeedBack.module.css
- src/components/NavBar/NavBar.jsx
Actualizacion feedBack y cambios en estilos del  boton login navbar
> Componente feedback, actualizacion estilos NavBar

- src/components/BtnFilter/BtnFilter.jsx
- src/components/Routine/Routine.jsx
- src/components/Routine/Routine.module.css
Agregué errores de las cards y los botones
> fixed cards rutines

- src/components/FeedBack/FeedBack.jsx
- src/components/FeedBack/FeedBack.module.css
- src/components/Ratingbystars/Ratingbystars.jsx
- src/redux/query/api.js
Conexion del feedBack con el back
Cambios en el componente de ratingByStars
> Conexion de FeedBack con el Back y cambio en el comp RatingbyStars

- src/App.jsx
- src/components/Home/Home.jsx
- src/components/ProductCard/ProductCard.jsx
- src/components/Products/Products.jsx
- src/components/Shop/Shop.jsx
- src/components/ThankYou/ThankYou.jsx
- src/redux/actions/defaultAction.js
- src/redux/query/ApiEcommerce.js
- src/redux/slices/defaultSlice.js
- src/redux/store/index.js
creacion del ecommerce en forma beta
> ecommerce in status beta

- src/components/Staff/Staff.jsx
- src/redux/actions/defaultAction.js
- src/redux/slices/defaultSlice.js
> no haganwebadas

- src/components/HeaderBtn/HeaderBtn.jsx
- src/components/HeaderBtn/HeaderBtn.module.css
- src/components/ProductCard/ProductCard.jsx
- src/components/Shop/Shop.jsx
- src/redux/slices/defaultSlice.js
- src/redux/store/index.js
> carrito de compras funcional

- src/components/HeaderBtn/HeaderBtn.jsx
- src/components/HeaderBtn/HeaderBtn.module.css
- src/components/NavBar/NavBar.jsx
- src/components/ShoppingCart/ShoppingCart.jsx
- src/components/ShoppingCart/ShoppingCart.module.css
resolvi bug en NavBar y cree un componente al carrito para que quede mas clean
> add ShoppingCart component and solve bugs in navBar

- src/components/AllRoutines/AllRoutines.jsx
- src/components/CardStaff/CardStaff.jsx
- src/components/Carousel/ImagenesEj.js
- src/components/DetailRoutine/DetailRoutine.jsx
- src/components/PrevRoutine/PrevRoutine.jsx
- src/components/PrevRoutines/PrevRoutines.jsx
- src/components/ProductCard/ProductCard.jsx
- src/components/Routine/Routine.jsx
- src/components/Shop/DatosFilter.js
- src/components/Shop/Filters.module.css
- src/components/Shop/Shop.jsx
- src/components/Staff/Helpers.js
- src/components/Staff/Staff.jsx
- src/redux/query/ApiEcommerce.js
> cambios para relajar

- src/App.jsx
- src/components/CardPlan/CardPlan.jsx
- src/components/CardPlan/CardPlan.module.css
- src/components/DetailRoutine/DetailRoutine.module.css
- src/components/Planes/Planes.module.css
- src/components/ProductCard/ProductCard.jsx
- src/components/ProductsInCar/ProductsInCar.jsx
- src/components/ProductsInCar/ProductsInCar.module.css
- src/components/Shopping/Shopping.jsx
- src/components/Shopping/Shopping.module.css
- styles.css
> component shopping

- src/components/Excercise/Excercise.module.css
- src/components/ProductsInCar/ProductsInCar.jsx
- src/components/ProductsInCar/ProductsInCar.module.css
- src/components/QuantitySelector/QuantitySelector.jsx
- src/components/QuantitySelector/QuantitySelector.module.css
- src/components/Shopping/Shopping.jsx
- src/components/Shopping/Shopping.module.css
- styles.css
> shopping finished

- src/components/FeedBack/FeedBack.jsx
- src/components/ShoppingCart/ShoppingCart.jsx
- src/components/ShoppingCart/ShoppingCart.module.css
aceptanme porfa, aron sos un capo total
> Linkeo del carrito, tranqui aaron

- src/components/ProductsInCar/ProductsInCar.jsx
- src/components/ProductsInCar/ProductsInCar.module.css
- src/components/Shopping/Shopping.jsx
> fixed productsInCar

- src/components/FeedBack/FeedBack.jsx
> fixeado  lo del fesback

- src/components/Footer/Footer.jsx
- src/components/Footer/Footer.module.css
> cambio de Footer

- src/components/BtnRoutines/BtnRoutines.jsx
- src/components/BtnRoutines/BtnRoutines.module.css
- src/components/Facilities/Facilities.jsx
- src/components/Facilities/Facilities.module.css
- src/components/NoMatch/NoMatch.jsx
- src/redux/actions/defaultAction.js
- src/redux/slices/defaultSlice.js
- src/redux/store/index.js
Logica para darle la funcion de editar las fotos en instalaciones al admin, por ahora hardcodeado para que cualquiera edite
> logica para func. de admin

- src/App.jsx
- src/main.jsx
> vercel to be tested

- src/components/Facilities/Facilities.jsx
Arroooooooooooon y Joseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
> arreglitos

- src/App.jsx
- src/components/Calendar/Calendar.jsx
- src/components/Calendar/Calendar.module.css
- src/components/NavBar/NavBar.jsx
Acetenlo,  que este ya  quedo  gucii, sujeto a cambios de estilo pq jose no me quiere
> Agrugue el calendario y el boton del mismo a la navbar

- package.json
- src/components/Facilities/Facilities.jsx
- src/components/Facilities/Facilities.module.css
- src/components/Facilities/Helpers.jsx
- src/components/FeedBack/FeedBack.jsx
- src/components/Footer/Footer.jsx
- src/components/Footer/Footer.module.css
La branch se llama dashboard pero se hicieron mejoras en otros componentes  xd
> mejoras varias y sweetalert

- src/components/DetailRoutine/DetailRoutine.module.css
- src/components/Excercise/Excercise.module.css
- src/components/HeaderBtn/HeaderBtn.jsx
- src/components/HeaderBtn/HeaderBtn.module.css
- src/components/NavBar/NavBar.jsx
- src/components/NavBar/NavBar.module.css
- src/components/ProductCard/ProductCard.jsx
- src/components/ProductsInCar/ProductsInCar.module.css
- src/components/QuantitySelector/QuantitySelector.jsx
- src/components/QuantitySelector/QuantitySelector.module.css
- src/components/Shop/Shop.jsx
- src/components/Shopping/Shopping.jsx
- src/components/ShoppingCart/ShoppingCart.jsx
- src/components/ShoppingCart/ShoppingCart.module.css
- styles.css
> TestColors2

- index.html
acetenme no se rompio nada lo juro
> Agregue el logo y cambie nombre en la pestaña del navegador

- src/components/Shop/DatosFilter.js
- src/components/Shop/FiltersShopContext.jsx
- src/components/Shop/Shop.jsx
- src/components/Shop/Shop.module.css
- src/main.jsx
- src/redux/query/ApiEcommerce.js
Hice el paginado, le aplique la persistencia de datos al mismo y a los filtros de la tienda con el context. En el formulario arregle un par de problemas. Falta validacion, css e ideas para mejorarlo
> Filtros y paginado tienda, + update form

- package.json
- src/components/Calendar/Calendar.jsx
- src/components/Calendar/Calendar.module.css
- src/components/ProductCard/ProductCard.jsx
- src/components/Products/Products.jsx
alertas toastify y cositas del calendario
> toastify and update calendar

- src/components/BtnFilter/BtnFilter.jsx
- src/components/FormRoutines/FormRoutines.jsx
- src/components/ProductCard/ProductCard.jsx
- src/components/Ratingbystars/Ratingbystars.jsx
- src/components/Shop/FiltersShopContext.jsx
- src/components/Staff/Staff.jsx
Alerta "producto agregado"
Alerta "producto no agregado, ya existe"
console.log eliminados
> product add alert

- src/components/AllRoutines/AllRoutines.jsx
- src/components/PrevRoutines/PrevRoutines.jsx
- src/components/Routine/Routine.jsx
- src/components/Routines/Routines.jsx
- src/components/Shop/FiltersShopContext.jsx
En el home se renderizan los favs si es que hay un minimo de 3 en favoritos..
> Favs funcionando

- src/App.jsx
- src/components/DetailRoutine/DetailRoutine.jsx
- src/components/DetailRoutine/DetailRoutine.module.css
- src/components/Loading/Loading.jsx
- src/components/ProductCard/ProductCard.jsx
- src/components/ProductsDetail/ProductsDetail.jsx
- src/components/ProductsDetail/ProductsDetail.module.css
- src/components/ProductsInCar/ProductsInCar.jsx
- src/components/QuantitySelector/QuantitySelector.jsx
- src/components/Shopping/Shopping.jsx
Aaaaaaaaron, terminé el componente detail, también actualicé unas cositas más, revisa el componente que te dejé comentarios importantes <3
> Component ProductsDetails and more updates

- src/components/Calendar/Calendar.jsx
- src/components/Calendar/Calendar.module.css
- src/components/Login/Login.css
- src/components/Login/Login.jsx
> Cambio de estilos en Landing y agregue cosa en Calendar

- src/redux/actions/defaultAction.js
Error de numero random en el carrito
> random number in item fixed

- src/components/Calendar/Calendar.jsx
- src/components/Calendar/Calendar.module.css
- src/components/Calendar/Calendarli.jsx
- src/components/Calendar/Calendarli.module.css
- src/components/FeedBack/FeedBack.jsx
- src/components/FeedBack/FeedBack.module.css
No toque ningun componente ajeno asi que tranca
> Hover en el calendar y validacion en el feedback

- src/components/Carousel/Banner.css
- src/components/Carousel/Banner.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/Dashboard.module.css
- src/components/Facilities/Facilities.jsx
- src/components/Facilities/Facilities.module.css
- src/components/Home/Home.jsx
- src/components/PrevShop/PrevShop.jsx
- src/components/PrevShop/PrevShop.module.css
Agregé el componente prev de la tienda al home, cambié estilos del carrusel y del dashboard
> dash board and carousel

- src/components/Home/Home.jsx
- src/components/ProductCard/ProductCard.jsx
- src/components/ProductsDetail/ProductsDetail.jsx
- src/components/ProductsInCar/ProductsInCar.jsx
- src/components/Shop/Shop.jsx
- src/components/Shopping/Shopping.jsx
- src/components/ShoppingCart/ShoppingCart.jsx
- src/redux/actions/defaultAction.js
- src/redux/query/ApiEcommerce.js
- src/redux/slices/defaultSlice.js
- src/redux/store/index.js
Se actualizo por completo el ecommerce, recuerden que ya no pueden comprar desde localhost
> ecommerce update

- src/components/ProductsDetail/ProductsDetail.jsx
- src/components/Shopping/Shopping.jsx
> fixed cart

- src/App.jsx
- src/components/AllRoutines/AllRoutines.jsx
- src/components/Carousel/Banner.jsx
- src/components/ProductCard/ProductCard.jsx
- src/components/Products/Products.jsx
- src/components/ProtectedRoute.jsx
- src/components/Routine/Routine.jsx
- src/components/Routines/Routines.jsx
- src/components/Shop/Shop.jsx
Oculte botones y protegí rutas, pero ahora estan comentadas asi las pueden usar
> AdmChanges

- src/App.jsx
- src/components/Calendar/Calendar.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/FeedBack/GetFeedbacks.jsx
- src/components/FeedBack/GetFeedbacks.module.css
- src/redux/query/api.js
> Agregue los feedbacks con su ruta ni  ma ni meno

- src/App.jsx
- src/components/CardPlan/CardPlan.jsx
- src/components/Planes/Planes.jsx
- src/components/SelectPlan/SelectPlan.jsx
- src/redux/actions/defaultAction.js
> planesAron

- src/components/CardPlan/CardPlan.jsx
- src/components/Facilities/Facilities.module.css
- src/components/Login/Login.css
- src/components/Login/Login.jsx
- src/components/NavBar/NavBar.jsx
- src/components/NavBar/NavBar.module.css
- src/components/Profile/Profile.jsx
- src/components/Profile/Profile.module.css
- src/components/SelectPlan/SelectPlan.jsx
- src/components/Staff/Staff.module.css
- styles.css
> Fixed profile, navbar, staff and facilities

- src/components/CardPlan/CardPlan.jsx
- src/components/Facilities/Facilities.jsx
- src/components/Facilities/Facilities.module.css
- src/components/Planes/Planes.jsx
- src/components/SelectPlan/SelectPlan.jsx
> Planes and facilities

- src/App.jsx
- src/components/Carousel/ImagenesEj.js
Cambie las restricciones de rutas en app, deje solo las restricciones para admin y staff.. Y cambie la foto del carrusel
> Changes in App & Carrousel

- src/components/FormProducts/EditProduct.jsx
- src/components/FormProducts/FormProducts.jsx
- src/components/FormProducts/FormProducts.module.css
> fixed Forms

- src/App.jsx
- src/components/FormProducts/EditProduct.jsx
Le añadí el select al edit de los productos. En app solo borre 2 espacios en vacios por TOC
> Add Select to Form
